version: '3.9'

services:
    chrome:
        container_name: qamqor_chrome
        image: selenium/standalone-chrome:113.0
        hostname: chrome
        ports:
            - ${CHROME_PORT}:${CHROME_PORT}
        networks:
            - web
        healthcheck:
            test: 'exit 0'

    mongodb:
        container_name: qamqor_mongodb
        image: mongo:7.0.6
        ports:
            - ${MONGO_PORT}:${MONGO_PORT}
        environment:
            MONGO_INIT_DB_DATABASE: ${MONGO_DB}
        volumes:
            - ./mongo:/data/db
        healthcheck:
            test: 'exit 0'
        networks:
            - web

    app:
        container_name: qamqor_app
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ./src:/src
        env_file: .env
        depends_on:
            mongodb:
                condition: service_healthy
            chrome:
                condition: service_healthy
        networks:
            - web

networks:
    web:
        driver: bridge
